package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/tool-chain-brain/tcb/pkg/models"
)

const dockerfileTemplate = `# ============================================================
#  Tool-Chain-Brain — Dockerfile.devenv
#  Generated by tcb: https://github.com/tool-chain-brain/tcb
#
#  Original system : {{.Meta.Hostname}} ({{.Meta.OS}}/{{.Meta.Arch}})
#  Scanned at      : {{.Meta.ScannedAt.Format "2006-01-02 15:04:05 UTC"}}
# ============================================================
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

# Base system utilities
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    wget \
    git \
    unzip \
    zip \
    ca-certificates \
    gnupg \
    lsb-release \
    software-properties-common \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Create non-root dev user
ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo "$USERNAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME
ENV HOME=/home/$USERNAME
WORKDIR /home/$USERNAME
{{range .Languages}}
{{- if eq .Name "go"}}
# ---- Go {{.Version}} ----
ENV GOVERSION={{.Version}}
RUN curl -OL "https://go.dev/dl/go${GOVERSION}.linux-amd64.tar.gz" \
    && sudo tar -C /usr/local -xzf "go${GOVERSION}.linux-amd64.tar.gz" \
    && rm "go${GOVERSION}.linux-amd64.tar.gz"
ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/home/dev/go
ENV GOBIN=/home/dev/go/bin
{{- end}}
{{- if eq .Name "node"}}
# ---- Node.js {{.Version}} via nvm ----
ENV NVM_DIR=/home/dev/.nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/HEAD/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install "{{.Version}}" \
    && nvm alias default "{{.Version}}" \
    && nvm use default
ENV PATH=$NVM_DIR/versions/node/v{{.Version}}/bin:$PATH
{{- end}}
{{- if or (eq .Name "python3") (eq .Name "python")}}
# ---- Python {{.Version}} via pyenv ----
ENV PYENV_ROOT=/home/dev/.pyenv
RUN curl https://pyenv.run | bash
ENV PATH=$PYENV_ROOT/bin:$PATH
RUN eval "$(pyenv init -)" \
    && pyenv install "{{.Version}}" \
    && pyenv global "{{.Version}}"
{{- end}}
{{- if eq .Name "rustc"}}
# ---- Rust {{.Version}} ----
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH=/home/dev/.cargo/bin:$PATH
{{- end}}
{{- if eq .Name "bun"}}
# ---- Bun {{.Version}} ----
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH=/home/dev/.bun/bin:$PATH
{{- end}}
{{- if eq .Name "deno"}}
# ---- Deno {{.Version}} ----
RUN curl -fsSL https://deno.land/install.sh | sh
ENV DENO_INSTALL=/home/dev/.deno
ENV PATH=$DENO_INSTALL/bin:$PATH
{{- end}}
{{- if eq .Name "java"}}
# ---- Java {{.Version}} ----
RUN sudo apt-get update && sudo apt-get install -y default-jdk && sudo rm -rf /var/lib/apt/lists/*
{{- end}}
{{end}}
{{range .PackageManagers}}
{{- if eq .Name "yarn"}}
# ---- Yarn ----
RUN npm install -g yarn
{{- end}}
{{- if eq .Name "pnpm"}}
# ---- pnpm ----
RUN npm install -g pnpm
{{- end}}
{{- if eq .Name "poetry"}}
# ---- Poetry ----
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH=/home/dev/.local/bin:$PATH
{{- end}}
{{- if eq .Name "uv"}}
# ---- uv ----
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
{{- end}}
{{end}}
{{range .InfraTools}}
{{- if eq .Name "kubectl"}}
# ---- kubectl ----
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl
{{- end}}
{{- if eq .Name "helm"}}
# ---- helm ----
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
{{- end}}
{{- if eq .Name "terraform"}}
# ---- terraform ----
RUN wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
       | sudo tee /etc/apt/sources.list.d/hashicorp.list \
    && sudo apt-get update && sudo apt-get install -y terraform \
    && sudo rm -rf /var/lib/apt/lists/*
{{- end}}
{{- if eq .Name "gh"}}
# ---- GitHub CLI ----
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
        | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
        | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && sudo apt-get update && sudo apt-get install -y gh \
    && sudo rm -rf /var/lib/apt/lists/*
{{- end}}
{{end}}

# ---- Git configuration ----
{{- with .Git}}
{{- if .UserName}}
RUN git config --global user.name   "{{.UserName}}"
{{- end}}
{{- if .UserEmail}}
RUN git config --global user.email  "{{.UserEmail}}"
{{- end}}
{{- if .DefaultBranch}}
RUN git config --global init.defaultBranch "{{.DefaultBranch}}"
{{- end}}
{{- if .CoreEditor}}
RUN git config --global core.editor "{{.CoreEditor}}"
{{- end}}
{{- if .PullRebase}}
RUN git config --global pull.rebase "{{.PullRebase}}"
{{- end}}
{{end}}

# ---- Workspace ----
RUN mkdir -p /home/dev/workspace
WORKDIR /home/dev/workspace

CMD ["/bin/bash"]
`

// WriteDockerfile generates Dockerfile.devenv in outDir.
func WriteDockerfile(tc *models.Toolchain, outDir string) (string, error) {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return "", err
	}

	funcMap := template.FuncMap{
		"join":  strings.Join,
		"lower": strings.ToLower,
	}

	tmpl, err := template.New("dockerfile").Funcs(funcMap).Parse(dockerfileTemplate)
	if err != nil {
		return "", fmt.Errorf("template parse error: %w", err)
	}

	dest := filepath.Join(outDir, "Dockerfile.devenv")
	f, err := os.Create(dest)
	if err != nil {
		return "", err
	}
	defer f.Close()

	if err := tmpl.Execute(f, tc); err != nil {
		return "", fmt.Errorf("template execute error: %w", err)
	}

	return dest, nil
}
