package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/tool-chain-brain/tcb/pkg/models"
)

const setupShTemplate = `#!/usr/bin/env bash
# ============================================================
#  Tool-Chain-Brain — setup.sh
#  Generated by tcb: https://github.com/tool-chain-brain/tcb
#
#  Original system : {{.Meta.Hostname}} ({{.Meta.OS}}/{{.Meta.Arch}})
#  Scanned at      : {{.Meta.ScannedAt.Format "2006-01-02 15:04:05 UTC"}}
# ============================================================
set -euo pipefail

# ---- colour helpers ----
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${GREEN}[tcb] $*${NC}"; }
warn()    { echo -e "${YELLOW}[tcb] $*${NC}"; }
err()     { echo -e "${RED}[tcb] $*${NC}" >&2; }

# ---- OS detection ----
OS="$(uname -s)"
ARCH="$(uname -m)"
info "Detected OS: $OS / $ARCH"

install_pkg() {
  local pkg="$1"
  case "$OS" in
    Darwin)  brew install "$pkg" 2>/dev/null || true ;;
    Linux)
      if command -v apt-get &>/dev/null; then
        sudo apt-get install -y "$pkg"
      elif command -v dnf &>/dev/null; then
        sudo dnf install -y "$pkg"
      elif command -v pacman &>/dev/null; then
        sudo pacman -S --noconfirm "$pkg"
      else
        warn "Unknown Linux package manager — install $pkg manually"
      fi ;;
    *) warn "Unsupported OS $OS — install $pkg manually" ;;
  esac
}

already_installed() {
  command -v "$1" &>/dev/null
}

# ============================================================
# Compilers — C / C++
# ============================================================
{{range .Compilers -}}
{{- if eq .Name "gcc"}}
if ! already_installed gcc; then
  info "Installing GCC…"
  if [ "$OS" = "Darwin" ]; then
    brew install gcc
  else
    install_pkg gcc
  fi
fi
{{- end}}
{{- if eq .Name "g++"}}
if ! already_installed g++; then
  info "Installing G++…"
  if [ "$OS" = "Darwin" ]; then
    brew install gcc   # g++ ships with gcc on macOS via brew
  else
    install_pkg g++
  fi
fi
{{- end}}
{{- if eq .Name "clang"}}
if ! already_installed clang; then
  info "Installing Clang…"
  if [ "$OS" = "Darwin" ]; then
    xcode-select --install 2>/dev/null || true
  else
    install_pkg clang
  fi
fi
{{- end}}
{{- if eq .Name "nasm"}}
if ! already_installed nasm; then
  info "Installing NASM assembler…"
  install_pkg nasm
fi
{{- end}}
{{- if eq .Name "musl-gcc"}}
if ! already_installed musl-gcc; then
  info "Installing musl-gcc…"
  install_pkg musl-tools
fi
{{- end}}
{{end}}

# ============================================================
# Cross-Compilers
# ============================================================
{{range .CrossCompilers -}}
{{- if eq .Name "osxcross"}}
# osxcross — cross-compile for macOS
if [ ! -d "${OSXCROSS_ROOT:-$HOME/osxcross}" ]; then
  info "osxcross not found. To install:"
  info "  git clone https://github.com/tpoechtrager/osxcross"
  info "  Place a MacOSX*.sdk.tar.xz in osxcross/tarballs/"
  info "  Then run: osxcross/build.sh"
  warn "Skipping osxcross — manual SDK acquisition required (Apple license)"
fi
{{- end}}
{{- if hasPrefix .Name "mingw-w64"}}
# mingw-w64 — cross-compile for Windows
if ! already_installed x86_64-w64-mingw32-gcc; then
  info "Installing mingw-w64…"
  if [ "$OS" = "Darwin" ]; then
    brew install mingw-w64
  else
    install_pkg mingw-w64
  fi
fi
{{- end}}
{{- if eq .Name "wine"}}
# Wine — run Windows binaries
if ! already_installed wine; then
  info "Installing Wine…"
  if [ "$OS" = "Darwin" ]; then
    brew install --cask wine-stable
  else
    sudo dpkg --add-architecture i386 2>/dev/null || true
    install_pkg wine
  fi
fi
{{- end}}
{{- if eq .Name "wine64"}}
if ! already_installed wine64; then
  info "Installing Wine64…"
  if [ "$OS" = "Darwin" ]; then
    brew install --cask wine-stable
  else
    install_pkg wine64
  fi
fi
{{- end}}
{{- if eq .Name "emcc"}}
# Emscripten — compile C/C++ to WebAssembly
if ! already_installed emcc; then
  info "Installing Emscripten…"
  git clone https://github.com/emscripten-core/emsdk.git "$HOME/emsdk"
  "$HOME/emsdk/emsdk" install latest
  "$HOME/emsdk/emsdk" activate latest
  # shellcheck source=/dev/null
  source "$HOME/emsdk/emsdk_env.sh"
fi
{{- end}}
{{- if eq .Name "android-ndk"}}
# Android NDK
if [ -z "${ANDROID_NDK_ROOT:-}" ] && [ -z "${ANDROID_NDK_HOME:-}" ]; then
  warn "Android NDK not found — install via Android Studio SDK Manager"
  warn "  or: sdkmanager 'ndk;{{.Version}}'"
fi
{{- end}}
{{end}}

# ============================================================
# Version Managers
# ============================================================
{{range .VersionManagers -}}
{{- if eq .Name "nvm"}}
# nvm
if ! already_installed nvm && [ ! -d "$HOME/.nvm" ]; then
  info "Installing nvm…"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/HEAD/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  # shellcheck source=/dev/null
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi
{{- end}}
{{- if eq .Name "volta"}}
# volta
if ! already_installed volta; then
  info "Installing volta…"
  curl https://get.volta.sh | bash
fi
{{- end}}
{{- if eq .Name "fnm"}}
# fnm
if ! already_installed fnm; then
  info "Installing fnm…"
  curl -fsSL https://fnm.vercel.app/install | bash
fi
{{- end}}
{{- if eq .Name "pyenv"}}
# pyenv
if ! already_installed pyenv && [ ! -d "$HOME/.pyenv" ]; then
  info "Installing pyenv…"
  curl https://pyenv.run | bash
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
fi
{{- end}}
{{- if eq .Name "rbenv"}}
# rbenv
if ! already_installed rbenv; then
  info "Installing rbenv…"
  install_pkg rbenv
fi
{{- end}}
{{- if eq .Name "rustup"}}
# rustup
if ! already_installed rustup; then
  info "Installing rustup…"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  # shellcheck source=/dev/null
  source "$HOME/.cargo/env"
fi
{{- end}}
{{- if eq .Name "sdkman"}}
# sdkman
if [ ! -d "$HOME/.sdkman" ]; then
  info "Installing SDKMAN…"
  curl -s "https://get.sdkman.io" | bash
fi
{{- end}}
{{- if eq .Name "asdf"}}
# asdf
if ! already_installed asdf; then
  info "Installing asdf…"
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
fi
{{- end}}
{{- if eq .Name "mise"}}
# mise
if ! already_installed mise; then
  info "Installing mise…"
  curl https://mise.run | sh
fi
{{- end}}
{{end}}

# ============================================================
# Language Runtimes
# ============================================================
{{range .Languages -}}
{{- if eq .Name "go"}}
# Go {{.Version}}
if ! already_installed go; then
  info "Installing Go {{.Version}}…"
  if [ "$OS" = "Darwin" ]; then
    brew install go
  else
    GO_VERSION="{{.Version}}"
    curl -OL "https://go.dev/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz"
    sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-${ARCH}.tar.gz"
    echo 'export PATH=$PATH:/usr/local/go/bin' >> "$HOME/.profile"
    rm "go${GO_VERSION}.linux-${ARCH}.tar.gz"
  fi
fi
{{- end}}
{{- if eq .Name "node"}}
# Node.js {{.Version}}
if ! already_installed node; then
  info "Installing Node.js {{.Version}}…"
  if already_installed nvm; then
    nvm install "{{.Version}}" && nvm use "{{.Version}}"
  elif already_installed volta; then
    volta install "node@{{.Version}}"
  elif already_installed fnm; then
    fnm install "{{.Version}}" && fnm use "{{.Version}}"
  else
    install_pkg nodejs
  fi
fi
{{- end}}
{{- if or (eq .Name "python3") (eq .Name "python")}}
# Python {{.Version}}
if ! already_installed python3; then
  info "Installing Python {{.Version}}…"
  if already_installed pyenv; then
    pyenv install "{{.Version}}" && pyenv global "{{.Version}}"
  else
    install_pkg python3
  fi
fi
{{- end}}
{{- if eq .Name "ruby"}}
# Ruby {{.Version}}
if ! already_installed ruby; then
  info "Installing Ruby {{.Version}}…"
  if already_installed rbenv; then
    rbenv install "{{.Version}}" && rbenv global "{{.Version}}"
  else
    install_pkg ruby
  fi
fi
{{- end}}
{{- if eq .Name "rustc"}}
# Rust {{.Version}}
if ! already_installed rustc; then
  info "Installing Rust {{.Version}}…"
  if already_installed rustup; then
    rustup install "{{.Version}}"
  else
    install_pkg rust
  fi
fi
{{- end}}
{{- if eq .Name "java"}}
# Java {{.Version}}
if ! already_installed java; then
  info "Installing Java {{.Version}}…"
  if already_installed sdk; then
    sdk install java "{{.Version}}"
  else
    install_pkg default-jdk
  fi
fi
{{- end}}
{{- if eq .Name "php"}}
# PHP {{.Version}}
if ! already_installed php; then
  info "Installing PHP {{.Version}}…"
  install_pkg php
fi
{{- end}}
{{- if eq .Name "dotnet"}}
# .NET {{.Version}}
if ! already_installed dotnet; then
  info "Installing .NET {{.Version}}…"
  if [ "$OS" = "Darwin" ]; then
    brew install --cask dotnet-sdk
  else
    wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --version "{{.Version}}"
    rm dotnet-install.sh
  fi
fi
{{- end}}
{{- if eq .Name "deno"}}
# Deno {{.Version}}
if ! already_installed deno; then
  info "Installing Deno {{.Version}}…"
  curl -fsSL https://deno.land/install.sh | sh
fi
{{- end}}
{{- if eq .Name "bun"}}
# Bun {{.Version}}
if ! already_installed bun; then
  info "Installing Bun {{.Version}}…"
  curl -fsSL https://bun.sh/install | bash
fi
{{- end}}
{{end}}

# ============================================================
# Package Managers
# ============================================================
{{range .PackageManagers -}}
{{- if eq .Name "yarn"}}
if ! already_installed yarn; then
  info "Installing yarn…"
  npm install -g yarn
fi
{{- end}}
{{- if eq .Name "pnpm"}}
if ! already_installed pnpm; then
  info "Installing pnpm…"
  npm install -g pnpm
fi
{{- end}}
{{- if eq .Name "poetry"}}
if ! already_installed poetry; then
  info "Installing poetry…"
  curl -sSL https://install.python-poetry.org | python3 -
fi
{{- end}}
{{- if eq .Name "uv"}}
if ! already_installed uv; then
  info "Installing uv…"
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
{{- end}}
{{end}}

# ============================================================
# Infrastructure & DevOps Tools
# ============================================================
{{range .InfraTools -}}
{{- if eq .Name "docker"}}
if ! already_installed docker; then
  info "Installing Docker…"
  if [ "$OS" = "Darwin" ]; then
    warn "Install Docker Desktop from https://www.docker.com/products/docker-desktop/"
  else
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "$USER"
  fi
fi
{{- end}}
{{- if eq .Name "kubectl"}}
if ! already_installed kubectl; then
  info "Installing kubectl…"
  if [ "$OS" = "Darwin" ]; then
    brew install kubectl
  else
    install_pkg kubectl
  fi
fi
{{- end}}
{{- if eq .Name "helm"}}
if ! already_installed helm; then
  info "Installing helm…"
  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
fi
{{- end}}
{{- if eq .Name "terraform"}}
if ! already_installed terraform; then
  info "Installing Terraform…"
  if [ "$OS" = "Darwin" ]; then
    brew tap hashicorp/tap && brew install hashicorp/tap/terraform
  else
    install_pkg terraform
  fi
fi
{{- end}}
{{- if eq .Name "aws"}}
if ! already_installed aws; then
  info "Installing AWS CLI…"
  if [ "$OS" = "Darwin" ]; then
    brew install awscli
  else
    install_pkg awscli
  fi
fi
{{- end}}
{{- if eq .Name "gcloud"}}
if ! already_installed gcloud; then
  info "Installing gcloud CLI…"
  if [ "$OS" = "Darwin" ]; then
    brew install --cask google-cloud-sdk
  else
    curl https://sdk.cloud.google.com | bash
  fi
fi
{{- end}}
{{- if eq .Name "ansible"}}
if ! already_installed ansible; then
  info "Installing Ansible…"
  if already_installed pip3; then
    pip3 install ansible
  else
    install_pkg ansible
  fi
fi
{{- end}}
{{- if eq .Name "gh"}}
if ! already_installed gh; then
  info "Installing GitHub CLI…"
  if [ "$OS" = "Darwin" ]; then
    brew install gh
  else
    install_pkg gh
  fi
fi
{{- end}}
{{end}}

# ============================================================
# Git Configuration
# ============================================================
{{- with .Git}}
{{- if .UserName}}
info "Configuring git…"
git config --global user.name   "{{.UserName}}"
{{- end}}
{{- if .UserEmail}}
git config --global user.email  "{{.UserEmail}}"
{{- end}}
{{- if .DefaultBranch}}
git config --global init.defaultBranch "{{.DefaultBranch}}"
{{- end}}
{{- if .CoreEditor}}
git config --global core.editor "{{.CoreEditor}}"
{{- end}}
{{- if .PullRebase}}
git config --global pull.rebase "{{.PullRebase}}"
{{- end}}
{{- if .PushDefault}}
git config --global push.default "{{.PushDefault}}"
{{- end}}
{{- if .CredentialHelper}}
git config --global credential.helper "{{.CredentialHelper}}"
{{- end}}
{{- if .CoreAutoCRLF}}
git config --global core.autocrlf "{{.CoreAutoCRLF}}"
{{- end}}
{{end}}

# ============================================================
# VS Code Extensions
# ============================================================
{{- with .Editor.VSCode}}
{{- if .Extensions}}
if already_installed code; then
  info "Installing VS Code extensions…"
  {{range .Extensions -}}
  code --install-extension "{{.}}" --force
  {{end -}}
fi
{{- end}}
{{end}}

info "✅  Tool-Chain-Brain setup complete!"
info "   Restart your shell or run: source ~/.bashrc (or ~/.zshrc)"
`

// WriteSetupSh generates the idempotent setup.sh install script.
func WriteSetupSh(tc *models.Toolchain, outDir string) (string, error) {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return "", err
	}

	funcMap := template.FuncMap{
		"join":      strings.Join,
		"lower":     strings.ToLower,
		"hasPrefix": strings.HasPrefix,
	}

	tmpl, err := template.New("setup").Funcs(funcMap).Parse(setupShTemplate)
	if err != nil {
		return "", fmt.Errorf("template parse error: %w", err)
	}

	dest := filepath.Join(outDir, "setup.sh")
	f, err := os.Create(dest)
	if err != nil {
		return "", err
	}
	defer f.Close()

	if err := tmpl.Execute(f, tc); err != nil {
		return "", fmt.Errorf("template execute error: %w", err)
	}

	// Make executable
	if err := os.Chmod(dest, 0755); err != nil {
		return "", err
	}

	return dest, nil
}
