package export

import (
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/tool-chain-brain/tcb/pkg/models"
)

// WriteYAML marshals the toolchain snapshot to toolchain.yaml in outDir.
func WriteYAML(tc *models.Toolchain, outDir string) (string, error) {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return "", err
	}

	out, err := yaml.Marshal(tc)
	if err != nil {
		return "", err
	}

	header := []byte("# Tool-Chain-Brain snapshot\n# Generated by tcb — https://github.com/tool-chain-brain/tcb\n---\n")
	dest := filepath.Join(outDir, "toolchain.yaml")

	if err := os.WriteFile(dest, append(header, out...), 0644); err != nil {
		return "", err
	}

	return dest, nil
}

// LoadYAML reads a toolchain.yaml file back into a Toolchain struct.
func LoadYAML(path string) (*models.Toolchain, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var tc models.Toolchain
	if err := yaml.Unmarshal(data, &tc); err != nil {
		return nil, err
	}
	return &tc, nil
}
